# Generated by Django 2.1.7 on 2019-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('shop_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop_details',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500, unique=True)),
                ('pincode', models.IntegerField(max_length=9)),
                ('gst_no', models.CharField(max_length=50, unique=True)),
                ('ph_no', models.IntegerField(max_length=10)),
                ('emailid', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
